spring.application.name=SpaceTravelPj
spring.profiles.include=mysql, api
spring.profiles.active=local

#Thymeleaf
spring.thymeleaf.prefix = classpath:templates/thymeleaf/
spring.thymeleaf.check-template-location = true
spring.thymeleaf.mode = HTML
spring.thymeleaf.encoding=UTF-8

mybatis.configuration.map-underscore-to-camel-case=true

# Caffeine 캐시 설정: 최대 10개 보관, 캐싱 후 6시간이 지나면 메모리에서 삭제
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=10,expireAfterWrite=6h




